[project]
name = "pyndianajones"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.3.2",
    "google-genai>=1.11.0",
    "rich>=14.0.0",
    "sqlalchemy>=2.0.40",
]
